### ISSUE TITLE
Access header error on localhost

### ISSUE THREAD

**Issue by oleg-demkovych** [akitten/linkedin-public-profile-parser#31]
When try to send request from local server, receive error: 

> Fetch API cannot load https://www.linkedin.com/in/nelsonic. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> 
> TypeError: Client request error: Failed to fetch
>     at TypeError (native)
> 
> Uncaught (in promise) TypeError: Cannot read property 'headers' of undefined

**Comment by nelsonic** [comment]
@olegdemkovych are you trying to run the request in the _browser_ ?

**Comment by oleg-demkovych** [comment]
@nelsonic yes. But not working on local server =(

**Comment by nelsonic** [comment]
@olegdemkovych this will not work in a browser because LinkedIn _blocks_ any/all "**_CORS**_" requests.
Apologies if the [_usage example_](https://github.com/akitten/linkedin-public-profile-parser#basic-usage) in the Readme is _unclear_.

**Comment by deepakmani** [comment]
Thank you for this answer.
I was attempting to make a request from the client and had the same issue. 
What is the difference between making an XHR request from the client and server?
Just noting that you can make a get request from a chrome extension background.html page when requesting permission in manifest.json
