### ISSUE TITLE
Nothing returned

### ISSUE THREAD

**Issue by pasko1983** [akitten/linkedin-public-profile-parser#36]
Hi, I'm trying to use the library but all i get in console when I launch the application is 

{
  "url": "https://it.linkedin.com/in/pascuccimarco"
}

which is the url I'm trying to parse. No error was found. I deployed the application on cloudno.de

**Comment by nelsonic** [comment]
@pasko1983 did you follow the instructions in the README? 
https://github.com/akitten/linkedin-public-profile-parser#basic-usage

**Comment by SimonLab** [comment]
Hi @pasko1983,

LinkedIn is blocking all requests form Amazon and other big providers to prevent web crawler getting their information. My guess is that cloudno.de is using either Amazon or one of the hosting providers who are blocked by LinkedIn. I'll try to find out what Cloudno.de is using or let us know if you know it already.

**Comment by pasko1983** [comment]
@nelsonic Yes, this is my code:
`var LP = require('linkedin-public-profile-parser');
var url = 'https://it.linkedin.com/in/pascuccimarco';
LP(url, function(err, data){
  console.log(JSON.stringify(data, null, 2)); // see below for sample output JSON
})`
I just changed the url var.
@SimonLab sorry I don't know. There is a list of providers blocked by Linkedin to be found somewhere?

**Comment by nelsonic** [comment]
@pasko1983 that code **_definitely works locally**_. I tried it and the output is: 

``` js
{
  "url": "https://it.linkedin.com/in/pascuccimarco",
  "connections": 78,
  "fullname": "Marco Pascucci",
  "location": "San Severo, Puglia, Italy",
  "current": "Sviluppatore Zoho Creator e Senior Developer presso CRMPARTNERS",
  "picture": "https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAZlAAAAJGQ2OGI0MjU5LTBiMTgtNGRlMS05ZGI4LWRlOTM2MTViMmUzNg.jpg",
  "summary": "Web e software developer con esperienza decennale. Freelance dal 2010, ho collaborato con molte aziende sviluppando software gestionali, siti istituzionali ed e-commerce. ",
  "skills": [
    "jQuery",
    "Sviluppo Web",
    "JavaScript",
    "PHP",
    "Informatica",
    "Drupal",
    "MySQL",
    "Sviluppo di software",
    "WordPress",
    "CSS",
    "CMS",
    "Java",
    "C",
    "C#",
    "C++",
    "Vedi 14+",
    "Photoshop",
    "Database",
    ".NET",
    "Server Microsoft SQL",
    "Zoho Creator",
    "Zoho CRM",
    "Zoho Reports",
    "Web design",
    "SQL",
    "Applicazioni Web",
    "E-commerce",
    "Assistenza clienti",
    "HTML5",
    "Bootstrap",
    "Visualizza meno"
  ],
  "languages": [
    "Italiano - ",
    "Inglese - "
  ],
  "experience": {
    "current": [
      {
        "title": "Sviluppatore Zoho Creator e Senior Developer",
        "org": "CRMPARTNERS",
        "date": "aprile 2015 – Presente (1 anno)",
        "location": "",
        "desc": "Sviluppo applicazioni Zoho Creator. Integrazione tra vari prodotti della suite Zoho e sistemi esterni tramite l&apos;utilizzo di API e service REST/SOAP. Data analyst tramite Zoho Reports."
      },
      {
        "title": "Programmatore",
        "org": "Freelance",
        "date": "settembre 2009 – Presente (6 anni 7 mesi)",
        "location": "",
        "desc": "Programmatore, Web Developer e Web Designer.<br>Sviluppo di siti web e software gestionali online, anche tramite l&apos;utilizzo di CMS quali Drupal e Wordpress. Amministratore Database (MySQL)."
      }
    ],
    "past": [
      {
        "title": "Addetto Help Desk ai \"Giochi del Mediterraneo\" Pescara 2009",
        "org": "Cyborg S.r.l.",
        "date": "giugno 2009 – luglio 2009 (2 mesi)",
        "location": "Pescara, Italia",
        "desc": "Supervisione delle infrastrutture informatiche, assistenza tecnica agli atleti e ai giornalisti. "
      }
    ]
  }
}
```

So the issue is the cloudno.de hosting as @SimonLab has suggested.
As for finding a list of the hosting providers that are blocked, we have not found such a list.
Its safe to assume that any "_major_" hosting provider will be blocked because they don't _want_ people extracting the profile data...
Is there a _reason_ why you _need_ to deploy your script to cloudno.de///?

**Comment by pasko1983** [comment]
@nelsonic I've just searched for a free hosting ready to deploy nodejs application, and cloudno were one option.

**Comment by nelsonic** [comment]
_All_ "_Free_" Hosting will _always_ get blocked...

**Comment by pasko1983** [comment]
@nelsonic So, if free hosting gets blocked and the majority of paid hosting gets blocked there are very little chances to make this node.js application work online...
At least it sounds reasonable enough, seen the API cutoff by Linkedin. Thanks for your help and time...

**Comment by nelsonic** [comment]
@pasko1983 if it helps, we use a Raspberry Pi to do the "parsing" of the profiles and then insert the _data_ into an app which is hosted by one of the major hosting providers... 
all for _learning_ purposes of course.
